# Generated by Django 6.0.4 on 2026-05-12 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_artifact_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='cyber_identity',
            field=models.ForeignKey(help_text='Persona on our side that speaks in this conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.cyberidentity'),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_members', to='core.role'),
        ),
    ]
