# Generated by Django 6.0.4 on 2026-06-17 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_organization_description_user_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassignment',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_assignments', to='core.cyberidentity'),
        ),
    ]
