# Generated by Django 6.0.4 on 2026-07-06 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_jobassignment_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='integration_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.integrationaccount'),
        ),
    ]
