# Generated by Django 6.0.4 on 2026-07-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_artifact_integration_account'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='integrationbridge',
            name='core_integr_integra_99f161_idx',
        ),
        migrations.RemoveIndex(
            model_name='integrationbridge',
            name='core_integr_identit_8a700b_idx',
        ),
        migrations.RemoveConstraint(
            model_name='integrationbridge',
            name='uniq_identity_integration_bridge',
        ),
        migrations.DeleteModel(
            name='IntegrationBridge',
        ),
    ]
