# Generated by Django 6.0.4 on 2026-07-08 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_integrationbridge_core_integr_integra_99f161_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='job_assignment',
            field=models.ForeignKey(blank=True, help_text="Job this memory was learned in; preserved even if the job's identity later changes.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='core.jobassignment'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='identity',
            field=models.ForeignKey(blank=True, help_text='Persona that owns this memory; preserved across the jobs that use this identity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='core.cyberidentity'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['job_assignment', 'memory_type', '-created'], name='core_memory_job_ass_c20413_idx'),
        ),
        migrations.AddConstraint(
            model_name='memory',
            constraint=models.CheckConstraint(condition=models.Q(('identity__isnull', False), ('job_assignment__isnull', False), _connector='OR'), name='memory_identity_or_job_required'),
        ),
    ]
